package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/99designs/gqlgen/graphql"
	"github.com/neirth/openlobster/internal/application/graphql/dto"
	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
	"github.com/neirth/openlobster/internal/domain/handlers"
	"github.com/neirth/openlobster/internal/domain/models"
)

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, conversationID string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return &generated.MutationResult{Success: true}, nil
	}
	if err := r.Deps.DeleteUser(ctx, conversationID); err != nil {
		return nil, err
	}
	return &generated.MutationResult{Success: true}, nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, conversationID string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return &generated.MutationResult{Success: true}, nil
	}
	if err := r.Deps.DeleteGroup(ctx, conversationID); err != nil {
		return nil, err
	}
	return &generated.MutationResult{Success: true}, nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, conversationID *string, channelID *string, content string) (*generated.MessageSentResult, error) {
	if r.Deps == nil {
		return nil, fmt.Errorf("sendMessage: deps not configured")
	}
	cid := ""
	if conversationID != nil {
		cid = *conversationID
	}
	if cid == "" && channelID != nil {
		cid = *channelID
	}
	if cid == "" {
		return nil, fmt.Errorf("sendMessage: conversationID or channelID required")
	}

	routeConversationID := cid
	routeChannelID := cid
	routeChannelType := "dashboard"
	routeIsGroup := false
	routeSenderName := ""

	if r.Deps != nil {
		if convs, err := r.Deps.Conversations(ctx); err == nil {
			if conv, ok := findConversationRoute(convs, cid); ok {
				if conv.ID != "" {
					routeConversationID = conv.ID
				}
				if conv.ChannelID != "" {
					routeChannelID = conv.ChannelID
				}
				if conv.ChannelType != "" {
					routeChannelType = conv.ChannelType
				}
				if conv.ParticipantName != "" {
					routeSenderName = conv.ParticipantName
				}
				routeIsGroup = conv.IsGroup
				routeChannelID, routeChannelType = resolveConversationRouteChannel(ctx, r.Deps, conv, routeChannelID, routeChannelType)
			}
		}
	}
	if strings.TrimSpace(routeSenderName) == "" {
		routeSenderName = routeChannelID
	}
	// If a MessageDispatcher is available, use unified handler and include
	// optional attachments passed as a JSON string in the GraphQL variables
	// (frontend declares `$attachments: String` and sends JSON there).
	if r.Deps.MessageDispatcher != nil {
		// Try to read attachments raw JSON from operation variables.
		op := graphql.GetOperationContext(ctx)
		var atts []models.Attachment
		if op != nil {
			if v, ok := op.Variables["attachments"]; ok && v != nil {
				// v may be a JSON string or an already-parsed structure. Marshal
				// it back to JSON bytes and unmarshal into the domain struct so
				// that JSON tags (e.g. "mime_type") are respected.
				var raw []byte
				switch vv := v.(type) {
				case string:
					if vv != "" {
						raw = []byte(vv)
					}
				default:
					if b, err := json.Marshal(vv); err == nil {
						raw = b
					}
				}
				if len(raw) > 0 {
					var parsed []models.Attachment
					if err := json.Unmarshal(raw, &parsed); err == nil {
						atts = parsed
					}
				}
			}
		}

		if err := r.Deps.MessageDispatcher.Handle(ctx, handlers.HandleMessageInput{
			ChannelID:      routeChannelID,
			Content:        content,
			ChannelType:    routeChannelType,
			ConversationID: &routeConversationID,
			SenderID:       routeChannelID,
			SenderName:     routeSenderName,
			FromDashboard:  true,
			IsGroup:        routeIsGroup,
			Attachments:    atts,
		}); err != nil {
			return nil, err
		}
		ok := true
		return &generated.MessageSentResult{Success: &ok}, nil
	}

	// Fallback: use existing deps.SendMessage behaviour when dispatcher not wired
	res, err := r.Deps.SendMessage(ctx, cid, content)
	if err != nil {
		return nil, err
	}
	if res == nil {
		ok := true
		return &generated.MessageSentResult{Success: &ok}, nil
	}
	return mappers.SendMessageResultToGenerated(res), nil
}

func findConversationRoute(conversations []dto.ConversationSnapshot, id string) (dto.ConversationSnapshot, bool) {
	for _, conv := range conversations {
		if conv.ID == id || conv.ChannelID == id {
			return conv, true
		}
	}
	return dto.ConversationSnapshot{}, false
}

type lastUserChannelFinder interface {
	GetLastChannelForUser(ctx context.Context, userID string) (channelType, platformChannelID string, err error)
}

type scopedLastUserChannelFinder interface {
	GetLastChannelForUserByChannel(ctx context.Context, userID, channelType string) (resolvedChannelType, platformChannelID string, err error)
}

func resolveConversationRouteChannel(ctx context.Context, deps *Deps, conv dto.ConversationSnapshot, channelID, channelType string) (string, string) {
	if deps == nil || deps.UserChannelRepo == nil || conv.IsGroup || conv.ParticipantID == "" {
		return channelID, channelType
	}
	if !needsPlatformChannelResolution(channelID, channelType) {
		return channelID, channelType
	}
	preferredChannelType := strings.TrimSpace(channelType)
	if preferredChannelType == "" {
		preferredChannelType = strings.TrimSpace(conv.ChannelType)
	}
	if preferredChannelType == "" {
		preferredChannelType = strings.TrimSpace(channelID)
	}
	if scopedFinder, ok := deps.UserChannelRepo.(scopedLastUserChannelFinder); ok && preferredChannelType != "" {
		resolvedType, resolvedID, err := scopedFinder.GetLastChannelForUserByChannel(ctx, conv.ParticipantID, preferredChannelType)
		if err != nil || !isResolvedPlatformChannelID(resolvedID, resolvedType, channelType) {
			return channelID, channelType
		}
		if strings.TrimSpace(channelType) == "" && strings.TrimSpace(resolvedType) != "" {
			channelType = resolvedType
		}
		return resolvedID, channelType
	}
	finder, ok := deps.UserChannelRepo.(lastUserChannelFinder)
	if !ok {
		return channelID, channelType
	}
	resolvedType, resolvedID, err := finder.GetLastChannelForUser(ctx, conv.ParticipantID)
	if err != nil || !isResolvedPlatformChannelID(resolvedID, resolvedType, channelType) {
		return channelID, channelType
	}
	if strings.TrimSpace(channelType) == "" && strings.TrimSpace(resolvedType) != "" {
		channelType = resolvedType
	}
	return resolvedID, channelType
}

func isResolvedPlatformChannelID(channelID, resolvedType, currentType string) bool {
	id := strings.TrimSpace(channelID)
	if id == "" {
		return false
	}
	if strings.EqualFold(id, "dashboard") {
		return false
	}
	if strings.TrimSpace(resolvedType) != "" && strings.EqualFold(id, resolvedType) {
		return false
	}
	if strings.TrimSpace(currentType) != "" && strings.EqualFold(id, currentType) {
		return false
	}
	return true
}

func needsPlatformChannelResolution(channelID, channelType string) bool {
	id := strings.TrimSpace(channelID)
	if id == "" {
		return true
	}
	typ := strings.TrimSpace(channelType)
	if typ == "" {
		return false
	}
	return strings.EqualFold(id, typ)
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context) ([]*generated.Conversation, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Conversations(ctx)
	if err != nil {
		return nil, err
	}
	return mappers.ConversationsToGenerated(list), nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, conversationID string, before *string, limit *int) ([]*generated.Message, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Messages(ctx, conversationID, before, limit)
	if err != nil {
		return nil, err
	}
	return mappers.MessagesToGenerated(list), nil
}
