package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
)

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, conversationID string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return &generated.MutationResult{Success: true}, nil
	}
	if err := r.Deps.DeleteUser(ctx, conversationID); err != nil {
		return nil, err
	}
	return &generated.MutationResult{Success: true}, nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, conversationID *string, channelID *string, content string) (*generated.MessageSentResult, error) {
	if r.Deps == nil {
		return nil, fmt.Errorf("sendMessage: deps not configured")
	}
	cid := ""
	if conversationID != nil {
		cid = *conversationID
	}
	if cid == "" && channelID != nil {
		cid = *channelID
	}
	if cid == "" {
		return nil, fmt.Errorf("sendMessage: conversationID or channelID required")
	}
	res, err := r.Deps.SendMessage(ctx, cid, content)
	if err != nil {
		return nil, err
	}
	if res == nil {
		ok := true
		return &generated.MessageSentResult{Success: &ok}, nil
	}
	return mappers.SendMessageResultToGenerated(res), nil
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context) ([]*generated.Conversation, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Conversations(ctx)
	if err != nil {
		return nil, err
	}
	return mappers.ConversationsToGenerated(list), nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, conversationID string, before *string, limit *int) ([]*generated.Message, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Messages(ctx, conversationID, before, limit)
	if err != nil {
		return nil, err
	}
	return mappers.MessagesToGenerated(list), nil
}
