package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"encoding/json"
	"log"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	pluginadapter "github.com/neirth/openlobster/internal/infrastructure/adapters/plugin"
)

// ReloadPlugins is the resolver for the reloadPlugins field.
func (r *mutationResolver) ReloadPlugins(ctx context.Context) ([]*generated.Plugin, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return []*generated.Plugin{}, nil
	}
	return pluginsFromRegistry(r.Deps.PluginRegistry.All()), nil
}

// UpdatePluginConfig is the resolver for the updatePluginConfig field.
func (r *mutationResolver) UpdatePluginConfig(ctx context.Context, pluginID string, configJSON string) (bool, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return false, nil
	}
	p := r.Deps.PluginRegistry.Get(pluginID)
	if p == nil {
		return false, nil
	}
	var cfg map[string]interface{}
	if err := json.Unmarshal([]byte(configJSON), &cfg); err != nil {
		return false, err
	}
	if schema, err := p.Schema(); err == nil {
		if err := pluginadapter.ValidateConfigSchema(schema, cfg); err != nil {
			return false, err
		}
	}
	input, err := json.Marshal(map[string]interface{}{"config": cfg})
	if err != nil {
		return false, err
	}
	if _, err := p.Call("configure", input); err != nil {
		log.Printf("plugins: updatePluginConfig %s: %v", pluginID, err)
		return false, err
	}
	if r.Deps != nil && r.Deps.ConfigWriter != nil {
		if _, err := r.Deps.ConfigWriter.Apply(ctx, map[string]interface{}{
			"pluginsSettings": map[string]interface{}{pluginID: cfg},
		}); err != nil {
			log.Printf("plugins: persist config %s failed: %v", pluginID, err)
			return false, err
		}
	}
	return true, nil
}

// Plugins is the resolver for the plugins field.
func (r *queryResolver) Plugins(ctx context.Context) ([]*generated.Plugin, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return []*generated.Plugin{}, nil
	}
	return pluginsFromRegistry(r.Deps.PluginRegistry.All()), nil
}
