package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"encoding/json"
	"log"
	"strings"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	pluginadapter "github.com/neirth/openlobster/internal/infrastructure/plugin"
)

// ReloadPlugins is the resolver for the reloadPlugins field.
func (r *mutationResolver) ReloadPlugins(ctx context.Context) ([]*generated.Plugin, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return []*generated.Plugin{}, nil
	}
	if r.Deps.ReloadPlugins != nil {
		if err := r.Deps.ReloadPlugins(ctx); err != nil {
			log.Printf("plugins: reload failed: %v", err)
			return nil, err
		}
	}
	return pluginsFromRegistry(r.Deps.PluginRegistry.All()), nil
}

// SetPluginEnabled is the resolver for the setPluginEnabled field.
func (r *mutationResolver) SetPluginEnabled(ctx context.Context, pluginID string, enabled bool) (bool, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return false, nil
	}
	p := r.Deps.PluginRegistry.Get(pluginID)
	if p == nil {
		return false, nil
	}
	if r.Deps.ConfigWriter == nil {
		return false, nil
	}
	payload := map[string]interface{}{}
	if p.Type() != "messaging" {
		payload["pluginsEnabled"] = map[string]interface{}{pluginID: enabled}
	}
	if p.Type() == "messaging" {
		if key := messagingChannelInputKeyForPluginID(pluginID); key != "" {
			payload[key] = enabled
		}
	}

	if _, err := r.Deps.ConfigWriter.Apply(ctx, payload); err != nil {
		log.Printf("plugins: persist enabled %s failed: %v", pluginID, err)
		return false, err
	}
	if r.Deps.ReloadPlugins != nil {
		if err := r.Deps.ReloadPlugins(ctx); err != nil {
			log.Printf("plugins: runtime reconcile after setPluginEnabled %s failed: %v", pluginID, err)
			return false, err
		}
	}
	return true, nil
}

// UpdatePluginConfig is the resolver for the updatePluginConfig field.
func (r *mutationResolver) UpdatePluginConfig(ctx context.Context, pluginID string, configJSON string) (bool, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return false, nil
	}
	p := r.Deps.PluginRegistry.Get(pluginID)
	if p == nil {
		return false, nil
	}
	var cfg map[string]interface{}
	if err := json.Unmarshal([]byte(configJSON), &cfg); err != nil {
		return false, err
	}
	if schema, err := p.Schema(); err == nil {
		if err := pluginadapter.ValidateConfigSchema(schema, cfg); err != nil {
			return false, err
		}
	}
	input, err := json.Marshal(map[string]interface{}{"config": cfg})
	if err != nil {
		return false, err
	}
	if p.Type() != "messaging" {
		if _, err := p.Call("configure", input); err != nil {
			// Persisting config should still succeed for plugins that do not yet
			// export a live configure entrypoint.
			if !strings.Contains(err.Error(), "function \"configure\" not exported") {
				log.Printf("plugins: updatePluginConfig %s: %v", pluginID, err)
				return false, err
			}
		}
	}
	if r.Deps != nil && r.Deps.ConfigWriter != nil {
		if _, err := r.Deps.ConfigWriter.Apply(ctx, map[string]interface{}{
			"pluginsSettings": map[string]interface{}{pluginID: cfg},
		}); err != nil {
			log.Printf("plugins: persist config %s failed: %v", pluginID, err)
			return false, err
		}
	}
	if r.Deps.ReloadPlugins != nil {
		if err := r.Deps.ReloadPlugins(ctx); err != nil {
			log.Printf("plugins: runtime reconcile after updatePluginConfig %s failed: %v", pluginID, err)
			return false, err
		}
	}
	return true, nil
}

// Plugins is the resolver for the plugins field.
func (r *queryResolver) Plugins(ctx context.Context) ([]*generated.Plugin, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return []*generated.Plugin{}, nil
	}
	return pluginsFromRegistry(r.Deps.PluginRegistry.All()), nil
}
