package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"encoding/json"
	"log"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/domain/ports"
)

// ReloadPlugins is the resolver for the reloadPlugins field.
func (r *mutationResolver) ReloadPlugins(ctx context.Context) ([]*generated.Plugin, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return []*generated.Plugin{}, nil
	}
	return pluginsFromRegistry(r.Deps.PluginRegistry.All()), nil
}

// UpdatePluginConfig is the resolver for the updatePluginConfig field.
func (r *mutationResolver) UpdatePluginConfig(ctx context.Context, pluginID string, configJSON string) (bool, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return false, nil
	}
	p := r.Deps.PluginRegistry.Get(pluginID)
	if p == nil {
		return false, nil
	}
	var cfg map[string]interface{}
	if err := json.Unmarshal([]byte(configJSON), &cfg); err != nil {
		return false, err
	}
	input, err := json.Marshal(map[string]interface{}{"config": cfg})
	if err != nil {
		return false, err
	}
	if _, err := p.Call("configure", input); err != nil {
		log.Printf("plugins: updatePluginConfig %s: %v", pluginID, err)
		return false, err
	}
	return true, nil
}

// Plugins is the resolver for the plugins field.
func (r *queryResolver) Plugins(ctx context.Context) ([]*generated.Plugin, error) {
	if r.Deps == nil || r.Deps.PluginRegistry == nil {
		return []*generated.Plugin{}, nil
	}
	return pluginsFromRegistry(r.Deps.PluginRegistry.All()), nil
}

// pluginsFromRegistry converts domain PluginPort slice to GraphQL Plugin slice.
func pluginsFromRegistry(plugins []ports.PluginPort) []*generated.Plugin {
	result := make([]*generated.Plugin, 0, len(plugins))
	for _, p := range plugins {
		schemaBytes, err := p.Schema()
		schemaStr := "{}"
		if err == nil && len(schemaBytes) > 0 {
			schemaStr = string(schemaBytes)
		}
		result = append(result, &generated.Plugin{
			ID:          p.ID(),
			Name:        p.Name(),
			Version:     p.Version(),
			Description: p.Description(),
			PluginType:  p.Type(),
			SchemaJSON:  schemaStr,
			Enabled:     true,
		})
	}
	return result
}
