package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/utils"
)

// AddTask is the resolver for the addTask field.
func (r *mutationResolver) AddTask(ctx context.Context, prompt string, schedule *string) (*generated.Task, error) {
	if r.Deps == nil {
		return nil, nil
	}
	id, err := r.Deps.AddTask(ctx, prompt, utils.PtrStr(schedule))
	if err != nil {
		return nil, err
	}
	if id == "" {
		return nil, nil
	}
	// Fetch the created task from the list
	list, err := r.Deps.Tasks(ctx)
	if err != nil {
		return nil, err
	}
	for _, t := range list {
		if t.ID == id {
			return mappers.TaskSnapshotToGeneratedFull(t), nil
		}
	}
	return nil, nil // Return nil if not found, let the UI handle the inconsistency
}

// CompleteTask is the resolver for the completeTask field.
func (r *mutationResolver) CompleteTask(ctx context.Context, taskID string) (bool, error) {
	if r.Deps == nil {
		return true, nil
	}
	err := r.Deps.CompleteTask(ctx, taskID)
	return err == nil, err
}

// RemoveTask is the resolver for the removeTask field.
func (r *mutationResolver) RemoveTask(ctx context.Context, taskID string) (bool, error) {
	if r.Deps == nil {
		return true, nil
	}
	err := r.Deps.RemoveTask(ctx, taskID)
	return err == nil, err
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, prompt string, schedule *string) (*generated.Task, error) {
	if r.Deps == nil {
		return nil, nil
	}
	if err := r.Deps.UpdateTask(ctx, id, prompt, utils.PtrStr(schedule)); err != nil {
		return nil, err
	}
	list, err := r.Deps.Tasks(ctx)
	if err != nil {
		return nil, err
	}
	for _, t := range list {
		if t.ID == id {
			return mappers.TaskSnapshotToGeneratedFull(t), nil
		}
	}
	return nil, nil
}

// ToggleTask is the resolver for the toggleTask field.
func (r *mutationResolver) ToggleTask(ctx context.Context, id string, enabled bool) (*generated.ToggleTaskResult, error) {
	if r.Deps == nil {
		return nil, nil
	}
	err := r.Deps.ToggleTask(ctx, id, enabled)
	result := &generated.ToggleTaskResult{
		Success: err == nil,
		ID:      &id,
		Enabled: &enabled,
	}
	if err != nil {
		errStr := err.Error()
		result.Error = &errStr
	}
	return result, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*generated.Task, error) {
	if r.Deps == nil {
		return nil, nil
	}
	list, err := r.Deps.Tasks(ctx)
	if err != nil {
		return nil, err
	}
	return mappers.TasksToGenerated(list), nil
}
